FROM php:7.2-fpm

WORKDIR /var/www
COPY . /var/www

RUN apt-get update && apt-get install -y \
    curl

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

